
# database settings
MySQL:
  host: 'localhost:3306'
  database: 'test'
  username: 'root'
  password: 'admin'

# amount of items collected to complete the quest
quest-amount: 2

# command to open collection menu
collection-command:
  command: ['colecao', 'coleção']
  description: 'Visualiza suas coleções.'
  usage: 'coleção'

# command to give collection
item-give-command:
  command: ['colecao give', 'coleção give']
  description: 'Envia item para um jogador.'
  permission: 'collection.give.command'
  usage: 'coleção give <jogador> <item> <quantidade>'

# command to redefine player collection
reset-collection-command:
  command: ['colecao reset', 'coleção reset']
  description: 'Redefine as coleções de um jogador.'
  permission: 'collection.reset.command'
  usage: 'coleção reset <jogador>'

# command to reload plugin
reload-command:
  command: ['colecao reload', 'coleção reload']
  description: 'Recarrega o plugin.'
  permission: 'collection.reload.command'
  usage: 'coleção reload'

# command to show available commands
help-command:
  command: ['colecao help', 'coleção help']
  description: 'Mostra os comandos disponíveis.'
  usage: 'coleção help'

# messages settings
messages:
  plugin-reloaded: '&aPlugin recarregado com sucesso!'
  player-not-found: '&cJogador não encontrado!'
  no-permission: '&cVocê não tem permissão para fazer isso!'

  must-be-player: '&cSomente jogadores podem fazer isso!'
  must-be-console: '&cEsse comando não é acessível para jogadores!'

  item-sent: '&aVocê enviou {amount}x {item} para o jogador {player}!'
  item-collected: '&aVocê coletou um item colecionável: &7{item_name}'
  item-already-collected: '&cVocê já coletou um item desse mesmo tipo!'
  items-redefined: '&aOs itens do jogador {player} foram redefinidiso!'

  invalid-item: '&cPor favor insira um item válido!'
  invalid-number: '&cPor favor insira um número válido!'
  invalid-player: '&cO jogador {0} não é um jogador válido!'
  invalid-command: '&cComando inválido tente: {0}'
  invalid-subcommand: '&cComando inválido tente: {0}'

  missing-argument: '&cVocê precisa inserir corretamente os argumentos! Uso correto: {1}'
  too-many-arguments: '&cComando inválido tente: {0}'
  no-subcommand-specified: '&cInsira o subcomando!'

  quest-completed:
    - ' '
    - '&eO jogador {player} achou todos os itens colecionáveis!'
    - ' '

items:
  # The item id, not modify after use of the item.
  1:
    # the item name
    name: 'Peitoral Verde'
    # item settings
    item:
      skull:
        enabled: false
        url: ''
      material: 'LEATHER_CHESTPLATE'
      data: 0
      name: '&aPeitoral Verde'
      lore:
        - '&7Esse é um item colecionável!'
        - ''
      color:
        r: 0
        g: 255
        b: 0

  2:
    # the item name
    name: 'Peitoral Vermelho'
    # item settings
    item:
      skull:
        enabled: false
        url: ''
      material: 'LEATHER_CHESTPLATE'
      data: 0
      name: '&cPeitoral Vermelho'
      lore:
        - '&7Esse é um item colecionável!'
        - ''
      color:
        r: 255
        g: 0
        b: 0

# items message localized on last line of item lore
items-placeholders:
  collect: '&eClique para coletar!'
  collected: '&8Coletado em: {item_collectedAt}'

# collect inventory settings
collect-inventory:
  # inventory title
  title: '&8Coleções'
  # item to open ranking
  ranking-item:
    # inventory slot
    slot: 49
    skull:
      enabled: false
      url: ''
    material: 'EMERALD'
    data: 0
    name: '&aTop'
    lore:
      - '&7Clique para visualizar o rank'

  # item to open the previous page
  previous-item:
    slot: 48
    skull:
      enabled: false
      url: ''
    material: 'ARROW'
    data: 0
    name: '&ePágina anterior'
    lore:
      - '&7Clique para voltar a página'

  # item to open the next page
  next-item:
    slot: 50
    skull:
      enabled: false
      url: ''
    material: 'ARROW'
    data: 0
    name: '&ePróxima página'
    lore:
      - '&7Clique para avançar a página'

# ranking inventory settings
ranking-inventory:
  # inventory title
  title: '&8Coleções - Top'
  # rank item format
  format:
    name: '&a#{ranking_pos} {ranking_name}'
    lore:
      - '&7Completada em: &f&e{ranking_completedAt}'

  # item to open menu
  menu-item:
    # inventory slot
    slot: 40
    skull:
      enabled: false
      url: ''
    material: 'PAPER'
    data: 0
    name: '&aMenu'
    lore:
      - '&7Clique para voltar ao menu'

  # item to open the previous page
  previous-item:
    slot: 39
    skull:
      enabled: false
      url: ''
    material: 'ARROW'
    data: 0
    name: '&ePágina anterior'
    lore:
      - '&7Clique para voltar a página'

  # item to open the next page
  next-item:
    slot: 41
    skull:
      enabled: false
      url: ''
    material: 'ARROW'
    data: 0
    name: '&ePróxima página'
    lore:
      - '&7Clique para avançar a página'